### ISSUE TITLE
shouldnt use partials in main layout 

### ISSUE THREAD

**Issue by Karyum** [FACN1/week7-SPN#39]
its preferred to use partials in views instead of the main layout

GO HERE http://stackoverflow.com/questions/24730861/what-is-the-difference-between-partial-view-and-layout

**Comment by m4v15** [comment]
I know this isn't my team, but where in that link does it say not to use partials in the main layout? It's a long link so I only skimmed it but couldn't see that

**Comment by Karyum** [comment]
i have this issue on your project to btw https://i.stack.imgur.com/Vamyx.png

**Comment by m4v15** [comment]
I don't think that image says not to use partials in layout

**Comment by m4v15** [comment]
In fact, below that image it says 

"You see the header and footer... you could even have partial view's there too."

**Comment by mattlub** [comment]
yeh, this is personal preference.

**Comment by Karyum** [comment]
yeah sorry guys i was misinformed 




(sherin's fault)
